"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowRight, CheckCircle2, Github, Shield, Terminal } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import Navbar from "@/components/layout/Navbar";
import { WaitlistForm } from "@/components/waitlist-form";
import { siteConfig } from "@/lib/site";

const controlLayer = [
  "Preview-first database changes",
  "Approval queue for risky writes",
  "Audit visibility by actor and environment",
  "Protected operations and blocked commands",
];

const pricingPreview = [
  {
    name: "Hobby",
    price: "$0",
    detail: "100 successful tool runs every 30 days.",
    href: "/docs",
    cta: "Start free",
  },
  {
    name: "Pro",
    price: "Paid",
    detail: "100,000 successful tool runs with hosted billing and upgrades.",
    href: "/pricing",
    cta: "See pricing",
  },
];

const homepageFaqs = [
  {
    question: "What does EnginiQ do for AI agents and Postgres?",
    answer:
      "EnginiQ gives AI agents structured Postgres tools for schema discovery, migrations, and parameterized queries, then adds guardrails, approvals, and audit visibility around risky operations.",
  },
  {
    question: "Does EnginiQ work with Cursor, Claude, and MCP clients?",
    answer:
      "Yes. EnginiQ exposes the same safe database workflow through a Node.js SDK, a CLI, and an MCP server that can be used by Cursor, Claude, and other MCP-compatible hosts.",
  },
  {
    question: "Why use EnginiQ instead of raw AI-generated SQL?",
    answer:
      "Raw SQL generated by an agent is difficult to trust in production. EnginiQ makes changes preview-first, blocks unsafe operations, and supports review and approval flows.",
  },
];

const organizationJsonLd = {
  "@context": "https://schema.org",
  "@type": "Organization",
  name: siteConfig.name,
  url: siteConfig.siteUrl,
  sameAs: [siteConfig.githubUrl],
};

const softwareJsonLd = {
  "@context": "https://schema.org",
  "@type": "SoftwareApplication",
  name: siteConfig.name,
  applicationCategory: "DeveloperApplication",
  operatingSystem: "Cross-platform",
  description: siteConfig.description,
  url: siteConfig.siteUrl,
  offers: {
    "@type": "Offer",
    price: "0",
    priceCurrency: "USD",
  },
};

const faqJsonLd = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: homepageFaqs.map((item) => ({
    "@type": "Question",
    name: item.question,
    acceptedAnswer: {
      "@type": "Answer",
      text: item.answer,
    },
  })),
};

export default function HomePage() {
  const [isVisible, setIsVisible] = useState(false);

  useEffect(() => {
    setIsVisible(true);
  }, []);

  return (
    <div className="min-h-screen bg-[#0A0A0A] text-zinc-50">
      <Navbar />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify([organizationJsonLd, softwareJsonLd, faqJsonLd]),
        }}
      />

      <main>
        <section className="relative overflow-hidden pb-20 pt-32 md:pb-32 md:pt-48">
          <div className="absolute inset-0 bg-[radial-gradient(circle_at_top,rgba(255,255,255,0.05),transparent_50%)]" />
          <div className="relative mx-auto max-w-6xl px-6 text-center">
            <div
              className={`space-y-8 transition-all duration-1000 ${
                isVisible ? "translate-y-0 opacity-100" : "translate-y-8 opacity-0"
              }`}
            >
              <div className="inline-flex items-center gap-2 rounded-full border border-white/[0.08] bg-white/[0.03] px-3 py-1.5 text-xs font-medium text-zinc-400">
                <span className="h-1.5 w-1.5 rounded-full bg-emerald-500" />
                <span>Safe Postgres control layer for AI agents</span>
              </div>
              <h1 className="text-6xl font-black leading-[1.02] tracking-tight text-white md:text-8xl">
                The safety layer
                <br />
                <span className="bg-gradient-to-b from-white to-zinc-500 bg-clip-text text-transparent">
                  for AI agents
                </span>
              </h1>
              <p className="mx-auto max-w-3xl text-lg leading-relaxed text-zinc-400 md:text-xl">
                Let AI agents work with Postgres without giving them
                production-destroying SQL access. EnginiQ adds guardrails,
                approvals, and audit visibility around real database workflows.
              </p>
            </div>

            <div
              className={`mt-10 flex flex-col items-center justify-center gap-4 transition-all duration-1000 delay-200 sm:flex-row ${
                isVisible ? "translate-y-0 opacity-100" : "translate-y-8 opacity-0"
              }`}
            >
              <Button
                asChild
                size="lg"
                className="group h-12 rounded-full bg-white px-8 text-base font-bold text-black hover:scale-105"
              >
                <Link href="/docs">
                  Start with the quickstart
                  <ArrowRight className="ml-2 h-5 w-5 transition-transform group-hover:translate-x-1" />
                </Link>
              </Button>
              <Button
                asChild
                variant="outline"
                size="lg"
                className="h-12 rounded-full border-white/10 px-8 text-base font-semibold text-zinc-200 hover:bg-white/5"
              >
                <Link href="/pricing">View pricing</Link>
              </Button>
            </div>

            <div className="mt-6 flex flex-wrap items-center justify-center gap-3 text-sm text-zinc-500">
              <Link href="/why-not-raw-ai-sql" className="hover:text-zinc-300">
                Why not raw AI SQL?
              </Link>
              <span className="text-zinc-800">/</span>
              <Link href="/supabase" className="hover:text-zinc-300">
                For Supabase teams
              </Link>
              <span className="text-zinc-800">/</span>
              <Link href="/demo" className="hover:text-zinc-300">
                Watch the proof flow
              </Link>
            </div>
          </div>
        </section>

        <section className="border-y border-white/[0.08] py-10">
          <div className="mx-auto flex max-w-6xl flex-wrap items-center justify-center gap-3 px-6 text-center text-sm text-zinc-400">
            <span className="rounded-full border border-white/[0.08] bg-white/[0.03] px-4 py-2">
              Approval-first database automation
            </span>
            <span className="rounded-full border border-white/[0.08] bg-white/[0.03] px-4 py-2">
              Postgres MCP server
            </span>
            <span className="rounded-full border border-white/[0.08] bg-white/[0.03] px-4 py-2">
              AI database migrations
            </span>
            <span className="rounded-full border border-white/[0.08] bg-white/[0.03] px-4 py-2">
              Cursor and Claude integrations
            </span>
          </div>
        </section>

        <section className="border-t border-white/[0.08] py-24">
          <div className="mx-auto max-w-6xl px-6">
            <div className="mb-10 flex flex-col gap-3 md:flex-row md:items-end md:justify-between">
              <div>
                <h2 className="text-3xl font-semibold tracking-tight text-zinc-100">
                  Built for safer database automation
                </h2>
                <p className="mt-3 max-w-3xl text-zinc-400">
                  Everything a team needs to let agents inspect schema, preview
                  changes, and keep risky database actions reviewable.
                </p>
              </div>
              <Button
                asChild
                className="bg-zinc-50 text-zinc-950 hover:bg-white"
              >
                <Link href="/demo">Run the 5-minute demo</Link>
              </Button>
            </div>
            <div className="grid gap-4 md:grid-cols-2">
              {controlLayer.map((item) => (
                <div
                  key={item}
                  className="flex items-center gap-3 rounded-2xl border border-white/[0.08] bg-white/[0.03] px-5 py-4 text-zinc-300"
                >
                  <CheckCircle2 className="h-4 w-4 text-emerald-400" />
                  <span>{item}</span>
                </div>
              ))}
            </div>
          </div>
        </section>

        <section className="border-t border-white/[0.08] py-24">
          <div className="mx-auto max-w-6xl px-6">
            <div className="mb-10 max-w-4xl">
              <h2 className="text-3xl font-semibold tracking-tight text-zinc-100 md:text-4xl">
                AI database workflows without raw production SQL
              </h2>
              <p className="mt-4 text-zinc-400">
                EnginiQ is built for teams that want AI-assisted Postgres work
                to be useful in real environments, not just impressive in a
                demo. Instead of asking an agent to guess at schema state and
                emit unrestricted SQL, the runtime gives it safe tools for
                schema discovery, guarded migrations, and parameterized queries.
              </p>
              <p className="mt-4 text-zinc-400">
                That matters for teams using Postgres in production, Supabase
                for app backends, or MCP-connected developer workflows in Cursor
                and Claude. Search demand will often come from phrases like
                "Postgres MCP", "AI database migrations", and "safe SQL for AI
                agents", and those are exactly the workflows this product is
                positioned to serve.
              </p>
            </div>
            <div className="grid gap-6 md:grid-cols-3">
              <Card className="rounded-2xl border-white/[0.08] bg-white/[0.03] p-6 text-zinc-50 shadow-none">
                <h3 className="text-xl font-semibold">Schema-aware by default</h3>
                <p className="mt-3 text-sm leading-7 text-zinc-400">
                  Agents can inspect tables, columns, and full schema state
                  before planning a mutation, which is materially safer than
                  prompting for SQL against stale assumptions.
                </p>
              </Card>
              <Card className="rounded-2xl border-white/[0.08] bg-white/[0.03] p-6 text-zinc-50 shadow-none">
                <h3 className="text-xl font-semibold">Preview-first changes</h3>
                <p className="mt-3 text-sm leading-7 text-zinc-400">
                  Dry-run, read-only, and approval-required paths let teams
                  preview a migration or table change before anything touches a
                  production database.
                </p>
              </Card>
              <Card className="rounded-2xl border-white/[0.08] bg-white/[0.03] p-6 text-zinc-50 shadow-none">
                <h3 className="text-xl font-semibold">Auditability and trust</h3>
                <p className="mt-3 text-sm leading-7 text-zinc-400">
                  EnginiQ turns AI database automation into an operational
                  workflow with traceability, approvals, and explicit policy
                  boundaries instead of prompt-only trust.
                </p>
              </Card>
            </div>
          </div>
        </section>

        <section className="border-t border-white/[0.08] py-24">
          <div className="mx-auto max-w-6xl px-6">
            <div className="mb-12 flex flex-col gap-3 md:flex-row md:items-end md:justify-between">
              <div>
                <h2 className="text-3xl font-semibold tracking-tight md:text-5xl">
                  Pricing
                </h2>
                <p className="mt-3 max-w-3xl text-zinc-400">
                  Pricing follows the billing model already wired into the app:
                  a free Hobby plan and a paid Pro upgrade for higher usage.
                </p>
              </div>
              <Button asChild className="bg-zinc-50 text-zinc-950 hover:bg-white">
                <Link href="/pricing">Open pricing</Link>
              </Button>
            </div>
            <div className="grid gap-6 md:grid-cols-3">
              {pricingPreview.map((plan) => (
                <Card
                  key={plan.name}
                  className="rounded-2xl border-white/[0.08] bg-white/[0.03] p-8 text-zinc-50 shadow-none"
                >
                  <p className="text-sm uppercase tracking-[0.18em] text-zinc-500">
                    {plan.name}
                  </p>
                  <h3 className="mt-3 text-3xl font-semibold">{plan.price}</h3>
                  <p className="mt-4 text-sm leading-7 text-zinc-400">
                    {plan.detail}
                  </p>
                  <Button
                    asChild
                    className="mt-6 w-full bg-zinc-50 text-zinc-950 hover:bg-white"
                  >
                    <Link href={plan.href}>{plan.cta}</Link>
                  </Button>
                </Card>
              ))}
            </div>
          </div>
        </section>

        <section className="border-t border-white/[0.08] py-24">
          <div className="mx-auto max-w-6xl px-6">
            <div className="mb-10 flex flex-col gap-3 md:flex-row md:items-end md:justify-between">
              <div>
                <h2 className="text-3xl font-semibold tracking-tight text-zinc-100">
                  Where buyers go next
                </h2>
                <p className="mt-3 max-w-3xl text-zinc-400">
                  Use these pages to convert different intents: comparison,
                  implementation, and pricing.
                </p>
              </div>
            </div>
            <div className="grid gap-6 md:grid-cols-3">
              <Link
                href="/why-not-raw-ai-sql"
                className="rounded-2xl border border-white/[0.08] bg-white/[0.03] p-8 transition-colors hover:border-white/[0.18]"
              >
                <Shield className="h-6 w-6 text-zinc-300" />
                <h3 className="mt-4 text-xl font-semibold">Why not raw AI SQL?</h3>
                <p className="mt-3 text-sm leading-7 text-zinc-400">
                  A buyer-facing comparison between improvised prompts and a
                  governed runtime with approvals.
                </p>
              </Link>
              <Link
                href="/supabase"
                className="rounded-2xl border border-white/[0.08] bg-white/[0.03] p-8 transition-colors hover:border-white/[0.18]"
              >
                <Terminal className="h-6 w-6 text-zinc-300" />
                <h3 className="mt-4 text-xl font-semibold">For Supabase teams</h3>
                <p className="mt-3 text-sm leading-7 text-zinc-400">
                  A dedicated onboarding and positioning page for the clearest
                  early-adopter workflow.
                </p>
              </Link>
              <Link
                href="/blog"
                className="rounded-2xl border border-white/[0.08] bg-white/[0.03] p-8 transition-colors hover:border-white/[0.18]"
              >
                <Github className="h-6 w-6 text-zinc-300" />
                <h3 className="mt-4 text-xl font-semibold">Blog and guides</h3>
                <p className="mt-3 text-sm leading-7 text-zinc-400">
                  Capture high-intent search demand around Postgres MCP, AI
                  migrations, and safe agent workflows.
                </p>
              </Link>
            </div>
          </div>
        </section>

        <section className="py-24">
          <div className="mx-auto max-w-4xl px-6">
            <Card className="rounded-[2.5rem] border-white/[0.08] bg-white/[0.02] p-8 text-center ring-1 ring-white/10 md:p-16">
              <h2 className="text-4xl font-bold tracking-tight text-white md:text-5xl">
                Ready to use EnginiQ?
              </h2>
              <p className="mx-auto mt-4 max-w-2xl text-lg text-zinc-400">
                Start with the quickstart, review pricing, or join the waitlist
                for hosted features.
              </p>
              <div className="mt-8 flex flex-col justify-center gap-4 sm:flex-row">
                <Button
                  asChild
                  size="lg"
                  className="h-12 rounded-full bg-white px-8 text-base font-bold text-black hover:scale-105"
                >
                  <Link href="/pricing">
                    Pricing and plans
                    <ArrowRight className="ml-2 h-4 w-4" />
                  </Link>
                </Button>
                <Button
                  asChild
                  variant="outline"
                  size="lg"
                  className="h-12 rounded-full border-white/10 px-8 text-base font-semibold text-zinc-200 hover:bg-white/5"
                >
                  <Link href="/waitlist">Talk to us</Link>
                </Button>
              </div>
              <div className="mx-auto mt-10 max-w-md">
                <p className="mb-4 text-xs font-bold uppercase tracking-[0.2em] text-zinc-500">
                  Join the waitlist
                </p>
                <WaitlistForm compact />
              </div>
            </Card>
          </div>
        </section>

        <section className="border-t border-white/[0.08] py-24">
          <div className="mx-auto max-w-4xl px-6">
            <div className="mb-10 text-center">
              <h2 className="text-3xl font-semibold tracking-tight text-zinc-100 md:text-4xl">
                Frequently asked questions
              </h2>
              <p className="mt-4 text-zinc-400">
                These answer the main search and buyer questions around AI
                agents, Postgres safety, and MCP-based workflows.
              </p>
            </div>
            <div className="grid gap-4">
              {homepageFaqs.map((item) => (
                <Card
                  key={item.question}
                  className="rounded-2xl border-white/[0.08] bg-white/[0.03] p-6 text-zinc-50 shadow-none"
                >
                  <h3 className="text-lg font-semibold text-zinc-100">
                    {item.question}
                  </h3>
                  <p className="mt-3 text-sm leading-7 text-zinc-400">
                    {item.answer}
                  </p>
                </Card>
              ))}
            </div>
          </div>
        </section>
      </main>

      <footer className="border-t border-white/[0.05] bg-[#0A0A0A] py-20">
        <div className="mx-auto flex max-w-7xl flex-col gap-8 px-6 md:flex-row md:items-end md:justify-between">
          <div>
            <div className="flex items-center space-x-3">
              <div className="flex h-9 w-9 items-center justify-center rounded-xl border border-white/10 bg-gradient-to-br from-zinc-700 to-zinc-800 shadow-xl">
                <span className="text-xs font-bold italic text-zinc-100">EQ</span>
              </div>
              <span className="text-lg font-bold tracking-tight text-white">
                {siteConfig.name}
              </span>
            </div>
            <p className="mt-4 max-w-xs text-sm leading-relaxed text-zinc-500">
              The safety layer between your AI agents and your production
              Postgres database.
            </p>
          </div>
          <div className="flex flex-wrap gap-4 text-sm text-zinc-500">
            <Link href="/pricing" className="hover:text-white">
              Pricing
            </Link>
            <Link href="/supabase" className="hover:text-white">
              Supabase teams
            </Link>
            <Link href="/why-not-raw-ai-sql" className="hover:text-white">
              Why not raw AI SQL?
            </Link>
            <a
              href={siteConfig.githubUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="hover:text-white"
            >
              GitHub
            </a>
          </div>
        </div>
      </footer>
    </div>
  );
}
